--
-- PostgreSQL database dump
--

-- Dumped from database version 17.0
-- Dumped by pg_dump version 17.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: dba
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO dba;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: dba
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: dba
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO dba;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: dba
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: dba
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO dba;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: dba
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: dba
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO dba;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: dba
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: dba
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO dba;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: dba
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: dba
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO dba;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: dba
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: dba
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO dba;

--
-- Name: django_site; Type: TABLE; Schema: public; Owner: dba
--

CREATE TABLE public.django_site (
    id integer NOT NULL,
    domain character varying(100) NOT NULL,
    name character varying(50) NOT NULL
);


ALTER TABLE public.django_site OWNER TO dba;

--
-- Name: django_site_id_seq; Type: SEQUENCE; Schema: public; Owner: dba
--

ALTER TABLE public.django_site ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_site_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notebook_errormessage; Type: TABLE; Schema: public; Owner: dba
--

CREATE TABLE public.notebook_errormessage (
    id bigint NOT NULL,
    name character varying(200) NOT NULL
);


ALTER TABLE public.notebook_errormessage OWNER TO dba;

--
-- Name: notebook_errormessage_id_seq; Type: SEQUENCE; Schema: public; Owner: dba
--

ALTER TABLE public.notebook_errormessage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notebook_errormessage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notebook_notebook; Type: TABLE; Schema: public; Owner: dba
--

CREATE TABLE public.notebook_notebook (
    created_at timestamp with time zone,
    id bigint NOT NULL,
    title character varying(200) NOT NULL,
    owner_id bigint
);


ALTER TABLE public.notebook_notebook OWNER TO dba;

--
-- Name: notebook_notebook_id_seq; Type: SEQUENCE; Schema: public; Owner: dba
--

ALTER TABLE public.notebook_notebook ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notebook_notebook_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notebook_record; Type: TABLE; Schema: public; Owner: dba
--

CREATE TABLE public.notebook_record (
    id bigint NOT NULL,
    number integer NOT NULL,
    title character varying(200) NOT NULL,
    created_at timestamp with time zone,
    text text NOT NULL,
    notebook_id bigint,
    template_id bigint,
    display_settings_id bigint
);


ALTER TABLE public.notebook_record OWNER TO dba;

--
-- Name: notebook_record_id_seq; Type: SEQUENCE; Schema: public; Owner: dba
--

ALTER TABLE public.notebook_record ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notebook_record_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notebook_recorddisplaysettings; Type: TABLE; Schema: public; Owner: dba
--

CREATE TABLE public.notebook_recorddisplaysettings (
    id bigint NOT NULL,
    _number_order integer NOT NULL,
    _title_order integer NOT NULL,
    _created_at_order integer NOT NULL,
    _text_order integer NOT NULL,
    _title_len integer NOT NULL,
    _text_len integer NOT NULL,
    datetime_format character varying NOT NULL
);


ALTER TABLE public.notebook_recorddisplaysettings OWNER TO dba;

--
-- Name: notebook_recorddisplaysettings_id_seq; Type: SEQUENCE; Schema: public; Owner: dba
--

ALTER TABLE public.notebook_recorddisplaysettings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notebook_recorddisplaysettings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notebook_recordtemplate; Type: TABLE; Schema: public; Owner: dba
--

CREATE TABLE public.notebook_recordtemplate (
    id bigint NOT NULL,
    name character varying(200) NOT NULL
);


ALTER TABLE public.notebook_recordtemplate OWNER TO dba;

--
-- Name: notebook_recordtemplate_id_seq; Type: SEQUENCE; Schema: public; Owner: dba
--

ALTER TABLE public.notebook_recordtemplate ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notebook_recordtemplate_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notebook_recordtemplate_parts; Type: TABLE; Schema: public; Owner: dba
--

CREATE TABLE public.notebook_recordtemplate_parts (
    id bigint NOT NULL,
    recordtemplate_id bigint NOT NULL,
    recordtemplatepart_id bigint NOT NULL
);


ALTER TABLE public.notebook_recordtemplate_parts OWNER TO dba;

--
-- Name: notebook_recordtemplate_parts_id_seq; Type: SEQUENCE; Schema: public; Owner: dba
--

ALTER TABLE public.notebook_recordtemplate_parts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notebook_recordtemplate_parts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notebook_recordtemplatepart; Type: TABLE; Schema: public; Owner: dba
--

CREATE TABLE public.notebook_recordtemplatepart (
    id bigint NOT NULL,
    name character varying(200) NOT NULL,
    value_type character varying(200) NOT NULL,
    sec_number integer NOT NULL
);


ALTER TABLE public.notebook_recordtemplatepart OWNER TO dba;

--
-- Name: notebook_recordtemplatepart_id_seq; Type: SEQUENCE; Schema: public; Owner: dba
--

ALTER TABLE public.notebook_recordtemplatepart ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notebook_recordtemplatepart_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_customuser; Type: TABLE; Schema: public; Owner: dba
--

CREATE TABLE public.users_customuser (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    email character varying(254) NOT NULL,
    is_admin boolean NOT NULL,
    is_superuser boolean NOT NULL
);


ALTER TABLE public.users_customuser OWNER TO dba;

--
-- Name: users_customuser_groups; Type: TABLE; Schema: public; Owner: dba
--

CREATE TABLE public.users_customuser_groups (
    id bigint NOT NULL,
    customuser_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.users_customuser_groups OWNER TO dba;

--
-- Name: users_customuser_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: dba
--

ALTER TABLE public.users_customuser_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_customuser_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_customuser_id_seq; Type: SEQUENCE; Schema: public; Owner: dba
--

ALTER TABLE public.users_customuser ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_customuser_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_customuser_user_permissions; Type: TABLE; Schema: public; Owner: dba
--

CREATE TABLE public.users_customuser_user_permissions (
    id bigint NOT NULL,
    customuser_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.users_customuser_user_permissions OWNER TO dba;

--
-- Name: users_customuser_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: dba
--

ALTER TABLE public.users_customuser_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_customuser_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_userscontrol; Type: TABLE; Schema: public; Owner: dba
--

CREATE TABLE public.users_userscontrol (
    id bigint NOT NULL
);


ALTER TABLE public.users_userscontrol OWNER TO dba;

--
-- Name: users_userscontrol_id_seq; Type: SEQUENCE; Schema: public; Owner: dba
--

ALTER TABLE public.users_userscontrol ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_userscontrol_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_userscontrol_users; Type: TABLE; Schema: public; Owner: dba
--

CREATE TABLE public.users_userscontrol_users (
    id bigint NOT NULL,
    userscontrol_id bigint NOT NULL,
    customuser_id bigint NOT NULL
);


ALTER TABLE public.users_userscontrol_users OWNER TO dba;

--
-- Name: users_userscontrol_users_id_seq; Type: SEQUENCE; Schema: public; Owner: dba
--

ALTER TABLE public.users_userscontrol_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_userscontrol_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: dba
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: dba
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: dba
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add site	6	add_site
22	Can change site	6	change_site
23	Can delete site	6	delete_site
24	Can view site	6	view_site
25	Can add Пользователь	7	add_customuser
26	Can change Пользователь	7	change_customuser
27	Can delete Пользователь	7	delete_customuser
28	Can view Пользователь	7	view_customuser
29	Can block and unblock users	7	can_block_user
30	Can add Управление пользователями	8	add_userscontrol
31	Can change Управление пользователями	8	change_userscontrol
32	Can delete Управление пользователями	8	delete_userscontrol
33	Can view Управление пользователями	8	view_userscontrol
34	Can add error message	9	add_errormessage
35	Can change error message	9	change_errormessage
36	Can delete error message	9	delete_errormessage
37	Can view error message	9	view_errormessage
38	Can add record display settings	10	add_recorddisplaysettings
39	Can change record display settings	10	change_recorddisplaysettings
40	Can delete record display settings	10	delete_recorddisplaysettings
41	Can view record display settings	10	view_recorddisplaysettings
42	Can add record template part	11	add_recordtemplatepart
43	Can change record template part	11	change_recordtemplatepart
44	Can delete record template part	11	delete_recordtemplatepart
45	Can view record template part	11	view_recordtemplatepart
46	Can add Блокнот	12	add_notebook
47	Can change Блокнот	12	change_notebook
48	Can delete Блокнот	12	delete_notebook
49	Can view Блокнот	12	view_notebook
50	Can add Запись	13	add_record
51	Can change Запись	13	change_record
52	Can delete Запись	13	delete_record
53	Can view Запись	13	view_record
54	Can add record template	14	add_recordtemplate
55	Can change record template	14	change_recordtemplate
56	Can delete record template	14	delete_recordtemplate
57	Can view record template	14	view_recordtemplate
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: dba
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: dba
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	sites	site
7	users	customuser
8	users	userscontrol
9	notebook	errormessage
10	notebook	recorddisplaysettings
11	notebook	recordtemplatepart
12	notebook	notebook
13	notebook	record
14	notebook	recordtemplate
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: dba
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2025-09-26 11:58:55.305334+03
2	contenttypes	0002_remove_content_type_name	2025-09-26 11:58:55.347335+03
3	auth	0001_initial	2025-09-26 11:58:55.848337+03
4	auth	0002_alter_permission_name_max_length	2025-09-26 11:58:55.86933+03
5	auth	0003_alter_user_email_max_length	2025-09-26 11:58:55.999334+03
6	auth	0004_alter_user_username_opts	2025-09-26 11:58:56.031338+03
7	auth	0005_alter_user_last_login_null	2025-09-26 11:58:56.071332+03
8	auth	0006_require_contenttypes_0002	2025-09-26 11:58:56.086338+03
9	auth	0007_alter_validators_add_error_messages	2025-09-26 11:58:56.109335+03
10	auth	0008_alter_user_username_max_length	2025-09-26 11:58:56.133329+03
11	auth	0009_alter_user_last_name_max_length	2025-09-26 11:58:56.172338+03
12	auth	0010_alter_group_name_max_length	2025-09-26 11:58:56.207332+03
13	auth	0011_update_proxy_permissions	2025-09-26 11:58:56.230338+03
14	auth	0012_alter_user_first_name_max_length	2025-09-26 11:58:56.260335+03
15	users	0001_initial	2025-09-26 11:58:56.513338+03
16	admin	0001_initial	2025-09-26 11:58:56.621337+03
17	admin	0002_logentry_remove_auto_add	2025-09-26 11:58:56.669341+03
18	admin	0003_logentry_add_action_flag_choices	2025-09-26 11:58:56.709337+03
19	notebook	0001_initial	2025-09-26 11:58:57.043336+03
20	sessions	0001_initial	2025-09-26 11:58:57.077332+03
21	sites	0001_initial	2025-09-26 11:58:57.181337+03
22	sites	0002_alter_domain_unique	2025-09-26 11:58:57.202336+03
23	notebook	0002_recorddisplaysettings_datetime_format	2025-09-26 12:56:15.740796+03
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: dba
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
zvpf5ocuvpd820ry0ehfuc6ra0xxthvk	.eJxVjEEOwiAQRe_C2pBCYVpcuvcMZGYYpGpoUtqV8e7apAvd_vfef6mI21ri1mSJU1JnZdTpdyPkh9QdpDvW26x5rusykd4VfdCmr3OS5-Vw_w4KtvKtPZhsxxTQB8-eg8sWugEhAGVmYwxDh8jgrO0HSSTII7HjLL04R6zeH-REOLw:1v24JR:VKy74a3fmE_AjKTvcWz7sxoBlwXf6FLol9mLqEY0Tnk	2025-10-10 12:00:21.343953+03
\.


--
-- Data for Name: django_site; Type: TABLE DATA; Schema: public; Owner: dba
--

COPY public.django_site (id, domain, name) FROM stdin;
1	example.com	example.com
\.


--
-- Data for Name: notebook_errormessage; Type: TABLE DATA; Schema: public; Owner: dba
--

COPY public.notebook_errormessage (id, name) FROM stdin;
\.


--
-- Data for Name: notebook_notebook; Type: TABLE DATA; Schema: public; Owner: dba
--

COPY public.notebook_notebook (created_at, id, title, owner_id) FROM stdin;
\N	1	блокнот 1	1
2025-09-26 15:20:13.248644+03	2	Мой опыт разработки сайта на Django	1
\.


--
-- Data for Name: notebook_record; Type: TABLE DATA; Schema: public; Owner: dba
--

COPY public.notebook_record (id, number, title, created_at, text, notebook_id, template_id, display_settings_id) FROM stdin;
1	1	Введение	2025-09-26 15:40:21+03	Я делаю эти записи (возможно, когда-то они станут книгой) по ряду причин. \r\n    Во-первых, хоть изучение документации по Django изначально создавало впечатление полного покрытия всех насущных вопросов начинающих пользователей этого инструмента ответами, впоследствии оказалось, что это не так. А читать всю документацию сплошняком до тех пор, пока не наткнешься на нужный пример или термин – то еще занятие. Да и гарантии, что найдешь – нет. Поэтому, в первую очередь, я буду освещать решение тех небольших проблем, которые неизбежно появляются в самом начале процесса разработки сайта с нуля при крайне малом опыте в таких вещах.\r\n    Во-вторых, хочется выстроить свои мысли в стройный ряд, в конструктивную последовательность: что, зачем, и в каком порядке стоит делать. Я не претендую на «лучшие практики», я очень много заимствую у таких же как и я начинающих программистов, чтобы расширить свой практический опыт, да и просто понять, что и зачем я делаю.	2	\N	\N
\.


--
-- Data for Name: notebook_recorddisplaysettings; Type: TABLE DATA; Schema: public; Owner: dba
--

COPY public.notebook_recorddisplaysettings (id, _number_order, _title_order, _created_at_order, _text_order, _title_len, _text_len, datetime_format) FROM stdin;
1	-1	-1	0	-1	10	10	
\.


--
-- Data for Name: notebook_recordtemplate; Type: TABLE DATA; Schema: public; Owner: dba
--

COPY public.notebook_recordtemplate (id, name) FROM stdin;
\.


--
-- Data for Name: notebook_recordtemplate_parts; Type: TABLE DATA; Schema: public; Owner: dba
--

COPY public.notebook_recordtemplate_parts (id, recordtemplate_id, recordtemplatepart_id) FROM stdin;
\.


--
-- Data for Name: notebook_recordtemplatepart; Type: TABLE DATA; Schema: public; Owner: dba
--

COPY public.notebook_recordtemplatepart (id, name, value_type, sec_number) FROM stdin;
\.


--
-- Data for Name: users_customuser; Type: TABLE DATA; Schema: public; Owner: dba
--

COPY public.users_customuser (id, password, last_login, username, first_name, last_name, is_staff, is_active, date_joined, email, is_admin, is_superuser) FROM stdin;
1	pbkdf2_sha256$1000000$E1KfaJ2lPaTF79lYFLACTR$6UyBB/VH/0IPinwQfvChabHx2Jmf2L6m2iWmrp6KbUU=	2025-09-26 12:00:21.333953+03	warhead999			t	t	2025-09-26 11:59:41.149549+03	Warhead999@mail.ru	f	t
\.


--
-- Data for Name: users_customuser_groups; Type: TABLE DATA; Schema: public; Owner: dba
--

COPY public.users_customuser_groups (id, customuser_id, group_id) FROM stdin;
\.


--
-- Data for Name: users_customuser_user_permissions; Type: TABLE DATA; Schema: public; Owner: dba
--

COPY public.users_customuser_user_permissions (id, customuser_id, permission_id) FROM stdin;
\.


--
-- Data for Name: users_userscontrol; Type: TABLE DATA; Schema: public; Owner: dba
--

COPY public.users_userscontrol (id) FROM stdin;
\.


--
-- Data for Name: users_userscontrol_users; Type: TABLE DATA; Schema: public; Owner: dba
--

COPY public.users_userscontrol_users (id, userscontrol_id, customuser_id) FROM stdin;
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dba
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dba
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dba
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 57, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dba
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dba
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 14, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dba
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 23, true);


--
-- Name: django_site_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dba
--

SELECT pg_catalog.setval('public.django_site_id_seq', 1, true);


--
-- Name: notebook_errormessage_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dba
--

SELECT pg_catalog.setval('public.notebook_errormessage_id_seq', 1, false);


--
-- Name: notebook_notebook_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dba
--

SELECT pg_catalog.setval('public.notebook_notebook_id_seq', 2, true);


--
-- Name: notebook_record_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dba
--

SELECT pg_catalog.setval('public.notebook_record_id_seq', 1, true);


--
-- Name: notebook_recorddisplaysettings_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dba
--

SELECT pg_catalog.setval('public.notebook_recorddisplaysettings_id_seq', 1, true);


--
-- Name: notebook_recordtemplate_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dba
--

SELECT pg_catalog.setval('public.notebook_recordtemplate_id_seq', 1, false);


--
-- Name: notebook_recordtemplate_parts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dba
--

SELECT pg_catalog.setval('public.notebook_recordtemplate_parts_id_seq', 1, false);


--
-- Name: notebook_recordtemplatepart_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dba
--

SELECT pg_catalog.setval('public.notebook_recordtemplatepart_id_seq', 1, false);


--
-- Name: users_customuser_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dba
--

SELECT pg_catalog.setval('public.users_customuser_groups_id_seq', 1, false);


--
-- Name: users_customuser_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dba
--

SELECT pg_catalog.setval('public.users_customuser_id_seq', 1, true);


--
-- Name: users_customuser_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dba
--

SELECT pg_catalog.setval('public.users_customuser_user_permissions_id_seq', 1, false);


--
-- Name: users_userscontrol_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dba
--

SELECT pg_catalog.setval('public.users_userscontrol_id_seq', 1, false);


--
-- Name: users_userscontrol_users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dba
--

SELECT pg_catalog.setval('public.users_userscontrol_users_id_seq', 1, false);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: dba
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: dba
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: dba
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: dba
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: dba
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: dba
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: dba
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: dba
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: dba
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: dba
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: dba
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: django_site django_site_domain_a2e37b91_uniq; Type: CONSTRAINT; Schema: public; Owner: dba
--

ALTER TABLE ONLY public.django_site
    ADD CONSTRAINT django_site_domain_a2e37b91_uniq UNIQUE (domain);


--
-- Name: django_site django_site_pkey; Type: CONSTRAINT; Schema: public; Owner: dba
--

ALTER TABLE ONLY public.django_site
    ADD CONSTRAINT django_site_pkey PRIMARY KEY (id);


--
-- Name: notebook_errormessage notebook_errormessage_name_key; Type: CONSTRAINT; Schema: public; Owner: dba
--

ALTER TABLE ONLY public.notebook_errormessage
    ADD CONSTRAINT notebook_errormessage_name_key UNIQUE (name);


--
-- Name: notebook_errormessage notebook_errormessage_pkey; Type: CONSTRAINT; Schema: public; Owner: dba
--

ALTER TABLE ONLY public.notebook_errormessage
    ADD CONSTRAINT notebook_errormessage_pkey PRIMARY KEY (id);


--
-- Name: notebook_notebook notebook_notebook_pkey; Type: CONSTRAINT; Schema: public; Owner: dba
--

ALTER TABLE ONLY public.notebook_notebook
    ADD CONSTRAINT notebook_notebook_pkey PRIMARY KEY (id);


--
-- Name: notebook_record notebook_record_pkey; Type: CONSTRAINT; Schema: public; Owner: dba
--

ALTER TABLE ONLY public.notebook_record
    ADD CONSTRAINT notebook_record_pkey PRIMARY KEY (id);


--
-- Name: notebook_recorddisplaysettings notebook_recorddisplaysettings_pkey; Type: CONSTRAINT; Schema: public; Owner: dba
--

ALTER TABLE ONLY public.notebook_recorddisplaysettings
    ADD CONSTRAINT notebook_recorddisplaysettings_pkey PRIMARY KEY (id);


--
-- Name: notebook_recordtemplate_parts notebook_recordtemplate__recordtemplate_id_record_2d2d9c4c_uniq; Type: CONSTRAINT; Schema: public; Owner: dba
--

ALTER TABLE ONLY public.notebook_recordtemplate_parts
    ADD CONSTRAINT notebook_recordtemplate__recordtemplate_id_record_2d2d9c4c_uniq UNIQUE (recordtemplate_id, recordtemplatepart_id);


--
-- Name: notebook_recordtemplate_parts notebook_recordtemplate_parts_pkey; Type: CONSTRAINT; Schema: public; Owner: dba
--

ALTER TABLE ONLY public.notebook_recordtemplate_parts
    ADD CONSTRAINT notebook_recordtemplate_parts_pkey PRIMARY KEY (id);


--
-- Name: notebook_recordtemplate notebook_recordtemplate_pkey; Type: CONSTRAINT; Schema: public; Owner: dba
--

ALTER TABLE ONLY public.notebook_recordtemplate
    ADD CONSTRAINT notebook_recordtemplate_pkey PRIMARY KEY (id);


--
-- Name: notebook_recordtemplatepart notebook_recordtemplatepart_pkey; Type: CONSTRAINT; Schema: public; Owner: dba
--

ALTER TABLE ONLY public.notebook_recordtemplatepart
    ADD CONSTRAINT notebook_recordtemplatepart_pkey PRIMARY KEY (id);


--
-- Name: users_customuser users_customuser_email_key; Type: CONSTRAINT; Schema: public; Owner: dba
--

ALTER TABLE ONLY public.users_customuser
    ADD CONSTRAINT users_customuser_email_key UNIQUE (email);


--
-- Name: users_customuser_groups users_customuser_groups_customuser_id_group_id_76b619e3_uniq; Type: CONSTRAINT; Schema: public; Owner: dba
--

ALTER TABLE ONLY public.users_customuser_groups
    ADD CONSTRAINT users_customuser_groups_customuser_id_group_id_76b619e3_uniq UNIQUE (customuser_id, group_id);


--
-- Name: users_customuser_groups users_customuser_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: dba
--

ALTER TABLE ONLY public.users_customuser_groups
    ADD CONSTRAINT users_customuser_groups_pkey PRIMARY KEY (id);


--
-- Name: users_customuser users_customuser_pkey; Type: CONSTRAINT; Schema: public; Owner: dba
--

ALTER TABLE ONLY public.users_customuser
    ADD CONSTRAINT users_customuser_pkey PRIMARY KEY (id);


--
-- Name: users_customuser_user_permissions users_customuser_user_pe_customuser_id_permission_7a7debf6_uniq; Type: CONSTRAINT; Schema: public; Owner: dba
--

ALTER TABLE ONLY public.users_customuser_user_permissions
    ADD CONSTRAINT users_customuser_user_pe_customuser_id_permission_7a7debf6_uniq UNIQUE (customuser_id, permission_id);


--
-- Name: users_customuser_user_permissions users_customuser_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: dba
--

ALTER TABLE ONLY public.users_customuser_user_permissions
    ADD CONSTRAINT users_customuser_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: users_customuser users_customuser_username_key; Type: CONSTRAINT; Schema: public; Owner: dba
--

ALTER TABLE ONLY public.users_customuser
    ADD CONSTRAINT users_customuser_username_key UNIQUE (username);


--
-- Name: users_userscontrol users_userscontrol_pkey; Type: CONSTRAINT; Schema: public; Owner: dba
--

ALTER TABLE ONLY public.users_userscontrol
    ADD CONSTRAINT users_userscontrol_pkey PRIMARY KEY (id);


--
-- Name: users_userscontrol_users users_userscontrol_users_pkey; Type: CONSTRAINT; Schema: public; Owner: dba
--

ALTER TABLE ONLY public.users_userscontrol_users
    ADD CONSTRAINT users_userscontrol_users_pkey PRIMARY KEY (id);


--
-- Name: users_userscontrol_users users_userscontrol_users_userscontrol_id_customus_28231d1e_uniq; Type: CONSTRAINT; Schema: public; Owner: dba
--

ALTER TABLE ONLY public.users_userscontrol_users
    ADD CONSTRAINT users_userscontrol_users_userscontrol_id_customus_28231d1e_uniq UNIQUE (userscontrol_id, customuser_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: dba
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: dba
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: dba
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: dba
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: dba
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: dba
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: dba
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: dba
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: django_site_domain_a2e37b91_like; Type: INDEX; Schema: public; Owner: dba
--

CREATE INDEX django_site_domain_a2e37b91_like ON public.django_site USING btree (domain varchar_pattern_ops);


--
-- Name: notebook_errormessage_name_ed78b842_like; Type: INDEX; Schema: public; Owner: dba
--

CREATE INDEX notebook_errormessage_name_ed78b842_like ON public.notebook_errormessage USING btree (name varchar_pattern_ops);


--
-- Name: notebook_notebook_owner_id_e8717836; Type: INDEX; Schema: public; Owner: dba
--

CREATE INDEX notebook_notebook_owner_id_e8717836 ON public.notebook_notebook USING btree (owner_id);


--
-- Name: notebook_record_display_settings_id_1bbdcd50; Type: INDEX; Schema: public; Owner: dba
--

CREATE INDEX notebook_record_display_settings_id_1bbdcd50 ON public.notebook_record USING btree (display_settings_id);


--
-- Name: notebook_record_notebook_id_a9e0fd8a; Type: INDEX; Schema: public; Owner: dba
--

CREATE INDEX notebook_record_notebook_id_a9e0fd8a ON public.notebook_record USING btree (notebook_id);


--
-- Name: notebook_record_template_id_48c477b8; Type: INDEX; Schema: public; Owner: dba
--

CREATE INDEX notebook_record_template_id_48c477b8 ON public.notebook_record USING btree (template_id);


--
-- Name: notebook_recordtemplate_parts_recordtemplate_id_ee560014; Type: INDEX; Schema: public; Owner: dba
--

CREATE INDEX notebook_recordtemplate_parts_recordtemplate_id_ee560014 ON public.notebook_recordtemplate_parts USING btree (recordtemplate_id);


--
-- Name: notebook_recordtemplate_parts_recordtemplatepart_id_48ce00af; Type: INDEX; Schema: public; Owner: dba
--

CREATE INDEX notebook_recordtemplate_parts_recordtemplatepart_id_48ce00af ON public.notebook_recordtemplate_parts USING btree (recordtemplatepart_id);


--
-- Name: users_customuser_email_6445acef_like; Type: INDEX; Schema: public; Owner: dba
--

CREATE INDEX users_customuser_email_6445acef_like ON public.users_customuser USING btree (email varchar_pattern_ops);


--
-- Name: users_customuser_groups_customuser_id_958147bf; Type: INDEX; Schema: public; Owner: dba
--

CREATE INDEX users_customuser_groups_customuser_id_958147bf ON public.users_customuser_groups USING btree (customuser_id);


--
-- Name: users_customuser_groups_group_id_01390b14; Type: INDEX; Schema: public; Owner: dba
--

CREATE INDEX users_customuser_groups_group_id_01390b14 ON public.users_customuser_groups USING btree (group_id);


--
-- Name: users_customuser_user_permissions_customuser_id_5771478b; Type: INDEX; Schema: public; Owner: dba
--

CREATE INDEX users_customuser_user_permissions_customuser_id_5771478b ON public.users_customuser_user_permissions USING btree (customuser_id);


--
-- Name: users_customuser_user_permissions_permission_id_baaa2f74; Type: INDEX; Schema: public; Owner: dba
--

CREATE INDEX users_customuser_user_permissions_permission_id_baaa2f74 ON public.users_customuser_user_permissions USING btree (permission_id);


--
-- Name: users_customuser_username_80452fdf_like; Type: INDEX; Schema: public; Owner: dba
--

CREATE INDEX users_customuser_username_80452fdf_like ON public.users_customuser USING btree (username varchar_pattern_ops);


--
-- Name: users_userscontrol_users_customuser_id_bb40dc7e; Type: INDEX; Schema: public; Owner: dba
--

CREATE INDEX users_userscontrol_users_customuser_id_bb40dc7e ON public.users_userscontrol_users USING btree (customuser_id);


--
-- Name: users_userscontrol_users_userscontrol_id_94e54428; Type: INDEX; Schema: public; Owner: dba
--

CREATE INDEX users_userscontrol_users_userscontrol_id_94e54428 ON public.users_userscontrol_users USING btree (userscontrol_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: dba
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: dba
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: dba
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: dba
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_users_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: dba
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_users_customuser_id FOREIGN KEY (user_id) REFERENCES public.users_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: notebook_notebook notebook_notebook_owner_id_e8717836_fk_users_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: dba
--

ALTER TABLE ONLY public.notebook_notebook
    ADD CONSTRAINT notebook_notebook_owner_id_e8717836_fk_users_customuser_id FOREIGN KEY (owner_id) REFERENCES public.users_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: notebook_record notebook_record_display_settings_id_1bbdcd50_fk_notebook_; Type: FK CONSTRAINT; Schema: public; Owner: dba
--

ALTER TABLE ONLY public.notebook_record
    ADD CONSTRAINT notebook_record_display_settings_id_1bbdcd50_fk_notebook_ FOREIGN KEY (display_settings_id) REFERENCES public.notebook_recorddisplaysettings(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: notebook_record notebook_record_notebook_id_a9e0fd8a_fk_notebook_notebook_id; Type: FK CONSTRAINT; Schema: public; Owner: dba
--

ALTER TABLE ONLY public.notebook_record
    ADD CONSTRAINT notebook_record_notebook_id_a9e0fd8a_fk_notebook_notebook_id FOREIGN KEY (notebook_id) REFERENCES public.notebook_notebook(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: notebook_record notebook_record_template_id_48c477b8_fk_notebook_notebook_id; Type: FK CONSTRAINT; Schema: public; Owner: dba
--

ALTER TABLE ONLY public.notebook_record
    ADD CONSTRAINT notebook_record_template_id_48c477b8_fk_notebook_notebook_id FOREIGN KEY (template_id) REFERENCES public.notebook_notebook(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: notebook_recordtemplate_parts notebook_recordtempl_recordtemplate_id_ee560014_fk_notebook_; Type: FK CONSTRAINT; Schema: public; Owner: dba
--

ALTER TABLE ONLY public.notebook_recordtemplate_parts
    ADD CONSTRAINT notebook_recordtempl_recordtemplate_id_ee560014_fk_notebook_ FOREIGN KEY (recordtemplate_id) REFERENCES public.notebook_recordtemplate(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: notebook_recordtemplate_parts notebook_recordtempl_recordtemplatepart_i_48ce00af_fk_notebook_; Type: FK CONSTRAINT; Schema: public; Owner: dba
--

ALTER TABLE ONLY public.notebook_recordtemplate_parts
    ADD CONSTRAINT notebook_recordtempl_recordtemplatepart_i_48ce00af_fk_notebook_ FOREIGN KEY (recordtemplatepart_id) REFERENCES public.notebook_recordtemplatepart(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_customuser_groups users_customuser_gro_customuser_id_958147bf_fk_users_cus; Type: FK CONSTRAINT; Schema: public; Owner: dba
--

ALTER TABLE ONLY public.users_customuser_groups
    ADD CONSTRAINT users_customuser_gro_customuser_id_958147bf_fk_users_cus FOREIGN KEY (customuser_id) REFERENCES public.users_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_customuser_groups users_customuser_groups_group_id_01390b14_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: dba
--

ALTER TABLE ONLY public.users_customuser_groups
    ADD CONSTRAINT users_customuser_groups_group_id_01390b14_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_customuser_user_permissions users_customuser_use_customuser_id_5771478b_fk_users_cus; Type: FK CONSTRAINT; Schema: public; Owner: dba
--

ALTER TABLE ONLY public.users_customuser_user_permissions
    ADD CONSTRAINT users_customuser_use_customuser_id_5771478b_fk_users_cus FOREIGN KEY (customuser_id) REFERENCES public.users_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_customuser_user_permissions users_customuser_use_permission_id_baaa2f74_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: dba
--

ALTER TABLE ONLY public.users_customuser_user_permissions
    ADD CONSTRAINT users_customuser_use_permission_id_baaa2f74_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_userscontrol_users users_userscontrol_u_customuser_id_bb40dc7e_fk_users_cus; Type: FK CONSTRAINT; Schema: public; Owner: dba
--

ALTER TABLE ONLY public.users_userscontrol_users
    ADD CONSTRAINT users_userscontrol_u_customuser_id_bb40dc7e_fk_users_cus FOREIGN KEY (customuser_id) REFERENCES public.users_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_userscontrol_users users_userscontrol_u_userscontrol_id_94e54428_fk_users_use; Type: FK CONSTRAINT; Schema: public; Owner: dba
--

ALTER TABLE ONLY public.users_userscontrol_users
    ADD CONSTRAINT users_userscontrol_u_userscontrol_id_94e54428_fk_users_use FOREIGN KEY (userscontrol_id) REFERENCES public.users_userscontrol(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

