# Generated by Django 5.2.3 on 2025-09-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ErrorMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название ошибки"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notebook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200, verbose_name="Название записной книжки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Блокнот",
                "verbose_name_plural": "блокноты",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.IntegerField(verbose_name="Номер страницы в блокноте"),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Заголовок записи",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(null=True, verbose_name="Дата создания"),
                ),
                ("text", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="RecordTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="имя шаблона страницы блокнота"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecordTemplatePart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="имя шаблона страницы блокнота"
                    ),
                ),
                (
                    "value_type",
                    models.CharField(max_length=200, verbose_name="тип содержимого"),
                ),
                (
                    "sec_number",
                    models.IntegerField(verbose_name="Порядковый номер в шаблоне"),
                ),
            ],
        ),
    ]
