# Generated by Django 5.2.3 on 2025-09-15 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ErrorMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Название ошибки"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecordTemplatePart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="имя шаблона страницы блокнота"
                    ),
                ),
                (
                    "value_type",
                    models.CharField(max_length=200, verbose_name="тип содержимого"),
                ),
                (
                    "sec_number",
                    models.IntegerField(verbose_name="Порядковый номер в шаблоне"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notebook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_created=True, null=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200, verbose_name="Название записной книжки"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notebooks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Блокнот",
                "verbose_name_plural": "блокноты",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.IntegerField(verbose_name="Номер страницы в блокноте"),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Заголовок записи",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(null=True, verbose_name="Дата создания"),
                ),
                ("text", models.TextField(blank=True)),
                (
                    "notebook",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="notebook.notebook",
                        verbose_name="Блокнот",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="this_template_Records",
                        to="notebook.notebook",
                        verbose_name="Блокнот",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecordTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="имя шаблона страницы блокнота"
                    ),
                ),
                (
                    "parts",
                    models.ManyToManyField(
                        to="notebook.recordtemplatepart", verbose_name="Получатели"
                    ),
                ),
            ],
        ),
    ]
