# Generated by Django 5.2.3 on 2025-09-13 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("notebook", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notebook",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notebooks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AddField(
            model_name="record",
            name="notebook",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="records",
                to="notebook.notebook",
                verbose_name="Блокнот",
            ),
        ),
        migrations.AddField(
            model_name="record",
            name="template",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="this_template_Records",
                to="notebook.notebook",
                verbose_name="Блокнот",
            ),
        ),
        migrations.AddField(
            model_name="recordtemplate",
            name="parts",
            field=models.ManyToManyField(
                to="notebook.recordtemplatepart", verbose_name="Получатели"
            ),
        ),
    ]
