# Generated by Django 5.2.3 on 2025-09-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notebook", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="created_at",
            field=models.DateTimeField(null=True, verbose_name="Дата создания"),
        ),
    ]
