# Generated by Django 5.2.3 on 2025-08-22 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notebook", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageTemplatePart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="имя шаблона страницы блокнота"
                    ),
                ),
                (
                    "value_type",
                    models.CharField(max_length=200, verbose_name="тип содержимого"),
                ),
                (
                    "sec_number",
                    models.IntegerField(verbose_name="Порядковый номер в шаблоне"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NotebookPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.IntegerField(verbose_name="Номер страницы в блокноте"),
                ),
                (
                    "notebook",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="notebook.notebook",
                        verbose_name="Блокнот",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="this_template_pages",
                        to="notebook.notebook",
                        verbose_name="Блокнот",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PageTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="имя шаблона страницы блокнота"
                    ),
                ),
                (
                    "parts",
                    models.ManyToManyField(
                        to="notebook.pagetemplatepart", verbose_name="Получатели"
                    ),
                ),
            ],
        ),
    ]
