# Generated by Django 5.2.3 on 2025-09-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notebook", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recorddisplaysettings",
            name="datetime_format",
            field=models.CharField(blank=True, default=""),
        ),
    ]
