# Generated by Django 5.2.3 on 2025-09-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notebook", "0002_pagetemplatepart_notebookpage_pagetemplate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notebook",
            name="title",
            field=models.CharField(
                max_length=200, unique=True, verbose_name="Название записной книжки"
            ),
        ),
    ]
