# Generated by Django 5.2.3 on 2025-09-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notebook", "0002_alter_record_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notebook",
            name="created_at",
            field=models.DateTimeField(
                auto_created=True, null=True, verbose_name="Дата создания"
            ),
        ),
    ]
