# Generated by Django 5.2.3 on 2025-09-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notebook", "0004_alter_notebook_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="notebookpage",
            name="title",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Заголовок записи"
            ),
        ),
    ]
