# Generated by Django 5.2.3 on 2025-09-03 09:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notebook", "0005_notebookpage_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="notebookpage",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата создания",
            ),
            preserve_default=False,
        ),
    ]
