# Generated by Django 5.2.3 on 2025-09-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notebook", "0007_alter_notebookpage_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notebookpage",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
    ]
