# Generated by Django 5.2.3 on 2025-09-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notebook", "0008_alter_notebookpage_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notebook",
            name="created_at",
            field=models.DateTimeField(verbose_name="Дата создания"),
        ),
    ]
