# Generated by Django 5.2.3 on 2025-09-03 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notebook", "0009_alter_notebook_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notebook",
            name="created_at",
        ),
    ]
