# Generated by Django 5.2.3 on 2025-09-03 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notebook", "0010_remove_notebook_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="notebook",
            name="creation_date",
            field=models.DateTimeField(
                auto_created=True,
                default=datetime.datetime(2025, 9, 3, 15, 47, 26, 275267),
                verbose_name="Дата создания",
            ),
            preserve_default=False,
        ),
    ]
