# Generated by Django 5.2.3 on 2025-09-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notebook", "0011_notebook_creation_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notebook",
            old_name="creation_date",
            new_name="created_at",
        ),
        migrations.AlterField(
            model_name="notebookpage",
            name="created_at",
            field=models.DateTimeField(verbose_name="Дата создания"),
        ),
    ]
