# Generated by Django 5.2.3 on 2025-09-03 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notebook", "0012_rename_creation_date_notebook_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotebookRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.IntegerField(verbose_name="Номер страницы в блокноте"),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Заголовок записи",
                    ),
                ),
                ("created_at", models.DateTimeField(verbose_name="Дата создания")),
                (
                    "notebook",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="notebook.notebook",
                        verbose_name="Блокнот",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="this_template_pages",
                        to="notebook.notebook",
                        verbose_name="Блокнот",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="NotebookPage",
        ),
    ]
