# Generated by Django 5.2.3 on 2025-09-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notebook", "0013_notebookrecord_delete_notebookpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="notebookrecord",
            name="text",
            field=models.TextField(blank=True),
        ),
    ]
